#!/bin/sh

ROOTDIR=`pwd`
export ROOTDIR=$ROOTDIR

if [ ! -f "$ROOTDIR/.config" ] ; then
	cp -fv "$ROOTDIR/configs/templates/n56u_dlna.config" "$ROOTDIR/.config"
fi

if [ ! -f "$ROOTDIR/.config" ] ; then
	echo "Project config file .config not found! Terminate."
	exit 1
fi

echo "-------------CLEAN-ALL---------------"
rm -rf $ROOTDIR/stage
make clean

rm -rfv $ROOTDIR/romfs
rm -rfv $ROOTDIR/images
rm -rfv $ROOTDIR/stage
. $ROOTDIR/.config
if [ -d $ROOTDIR/merge/$CONFIG_FIRMWARE_PRODUCT_ID ]; then 
	sudo rm -rf $ROOTDIR/merge/$CONFIG_FIRMWARE_PRODUCT_ID
fi

rm -f tools/mkimage/.depend
rm -f tools/xz/Doxyfile
rm -f tools/xz/Makefile
rm -f tools/xz/autom4te.cache/output.*
rm -f tools/xz/autom4te.cache/requests
rm -f tools/xz/autom4te.cache/traces.*
rm -f tools/xz/config.h
rm -f tools/xz/config.log
rm -f tools/xz/config.status
rm -f tools/xz/debug/.deps/*.Po
rm -f tools/xz/debug/Makefile
rm -f tools/xz/libtool
rm -f tools/xz/stamp-h1
rm -f tools/xz/tests/.deps/*.Po
rm -f tools/xz/tests/Makefile
